### ISSUE TITLE
Error: "payload is required"

### ISSUE THREAD

**Issue by artman325** [Qbix/Platform-History-v2#1866]
**Set**
Qbix/Platform (v1.0) [564bfeeffca5238a9903e782b533710588896658](https://github.com/Qbix/Platform/tree/564bfeeffca5238a9903e782b533710588896658)
plugins Users 1.0

**Step to reproduce**
- clean up cookies
- call `Q.Users.login();` in console and sign up via email as **User1**;
- call `Q.Users.login();` again and sign up via web3 
- call `Q.Users.logout()`;
- call `Q.Users.login();` in console and sign up via email as **User2**;
- call `Q.Users.login();` again and sign up via web3 

**Current Result:** appear js dialog with message "payload is required";

**Expected Result:** no errors. if there are no such wallet in the system then make wallet belong to current user. otherwise - logout(for current user) and sign up with wallet of existstin user in database
![image](https://user-images.githubusercontent.com/3704060/180302799-96655ab8-fc65-4756-92f9-09458dfbd610.png)

**Comment by EGreg** [comment]
This is now fixed
